---
collections:
  - name: https://github.com/companieshouse/ansible-collections.git#ch_collections
    version: 0.1.146
    type: git
  - name: ansible.posix
    version: 1.5.4
  - name: companieshouse.security
    version: 1.0.21

roles:
  - src: https://github.com/ansible-lockdown/AMAZON2023-CIS
    name: AMAZON2023-CIS
    version: 1.2.4
